# Generated by Django 3.0.8 on 2020-09-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('usedPromo', models.CharField(max_length=128)),
                ('totalDiscount', models.IntegerField(default=0)),
                ('user_email', models.EmailField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='UsedPromoUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promoCode', models.CharField(max_length=128)),
                ('user_email', models.EmailField(max_length=40)),
            ],
        ),
    ]
