# Generated by Django 3.0.8 on 2020-09-01 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couponAPi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
