# Generated by Django 3.0.8 on 2020-09-01 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couponAPi', '0002_promo_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='gender',
            field=models.CharField(default='', max_length=10),
        ),
    ]
